version: '3'

services:
  db:
    image: postgres:10.6-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  web:
    env_file: .env
    build: .
    container_name: "wine_reviews_web"
    command: ./entrypoint.sh
    volumes:
      - .:/src
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
